modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="AGPL-3.0"
issueTrackerURL="https://github.com/zach2039/oldguns/issues" #optional
[[mods]] #mandatory
modId="factorymade" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Factory Made" #mandatory
updateJSONURL="https://www.zach2039.com/mods/factorymade/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/factory-made" #optional
logoFile="factorymade.png" #optional
credits="Contributors, artists, and those who helped test!" #optional
authors="Zach2039" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Blocks for your next industrial style build.
'''
[[dependencies.factorymade]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.0.98,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.factorymade]]
    modId="jei"
    mandatory=false
    versionRange="[1.19,)"
    ordering="NONE"
    side="CLIENT"
